templates:
  - /etc/alertmanager/templates/*.tmpl
route:
  receiver: slack
  group_by: ['...']
  group_wait: 0s
  group_interval: 1m
  repeat_interval: 4h
receivers:
- name: slack
  slack_configs:
  - send_resolved: true
    api_url: <%= @slack_webhook_url %>
    color: '{{ template "custom.slack.color" . }}'
    fallback: '{{ template "custom.subject" . }}'
    text: '{{ template "custom.slack.text" . }}'
    title: '{{ template "custom.subject" . }}'
    title_link: '{{ template "common.grafana.alerting.alert_rules.url" . }}'