global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
  - '/etc/prometheus/rules.d/*.yml'
scrape_config_files:
  - '/etc/prometheus/scrape_config.d/*.yml'
scrape_configs:
  - job_name: file_sd
    file_sd_configs:
      - files:
        - '/etc/prometheus/file_sd.d/*.yml'
        refresh_interval: 1m
  - job_name: 'blackbox_http_2xx'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - '/etc/prometheus/blackbox_http_2xx.d/*.yml'
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:<%= @blackbox_exporter_port %>
  - job_name: 'blackbox_http_302'
    metrics_path: /probe
    params:
      module: [http_302]
    file_sd_configs:
      - files:
        - '/etc/prometheus/blackbox_http_302.d/*.yml'
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:<%= @blackbox_exporter_port %>
  - job_name: 'blackbox_http_401'
    metrics_path: /probe
    params:
      module: [http_401]
    file_sd_configs:
      - files:
        - '/etc/prometheus/blackbox_http_401.d/*.yml'
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:<%= @blackbox_exporter_port %>
  - job_name: 'blackbox_ssh_banner'
    metrics_path: /probe
    params:
      module: [ssh_banner]
    file_sd_configs:
      - files:
        - '/etc/prometheus/blackbox_ssh_banner.d/*.yml'
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:<%= @blackbox_exporter_port %>
  - job_name: 'brother_exporter'
    metrics_path: /probe
    file_sd_configs:
      - files:
        - '/etc/prometheus/brother_exporter.d/*.yml'
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_address
      - source_labels: [__param_address]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:<%= @brother_exporter_port %>
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 127.0.0.1:<%= @alertmanager_port %>
